import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { ThemeProvider } from '@/components/layouts/ThemeProvider'
import Header from '@/components/layouts/Header'
import SessionProviderWrapper from '@/components/layouts/SessionProviderWrapper'
import { NextIntlClientProvider, useMessages } from 'next-intl'

export const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
})

export const metadata: Metadata = {
  title: 'NextJS - Keycloak - Vimeo',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode
  params: { locale: 'es' | 'en' }
}) {
  const messages = useMessages()

  return (
    <SessionProviderWrapper>
      <html lang={locale}>
        <body
          className={cn(
            'min-h-screen bg-background font-sans antialiased',
            fontSans.variable
          )}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            disableTransitionOnChange
          >
            <NextIntlClientProvider locale={locale} messages={messages}>
              {children}
            </NextIntlClientProvider>
          </ThemeProvider>
        </body>
      </html>
    </SessionProviderWrapper>
  )
}
